version: '2'
services:
  nginx:
    extends:
      file: compose-common.yml
      service: nginx
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        syslog-tag: "application/nginx"
    depends_on:
    - php
  php:
    extends:
      file: compose-common.yml
      service: php
    logging:
      driver: "syslog"
      options:
        syslog-facility: "local0"
        syslog-tag: "application/php"