version: '2'
services:
  nginx:
    extends:
      file: common-compose.yml
      service: nginx
    depends_on:
    - php
  php:
    extends:
      file: common-compose.yml
      service: php
  mongo:
    extends:
      file: common-compose.yml
      service: mongo